### ISSUE TITLE
Non-Windows Support

### ISSUE THREAD

**Issue by EmperorPenguin18** [Sorrow446/MUR_Go#1]
I would likely use this program on Linux. I am also not very familiar with Go. Is it possible you could provide installation instructions for non-Windows users?

**Comment by Sorrow446** [comment]
Sorry, I only started building for Linux and Mac too after this project. Just added binaries for those.

From binary:
1. CD into binary's path. `cd <path>`.
2. Make binary executable. `chmod +x mur_linux_x64`.
3. Run. `./mur_linux_x64 <urls>`

From source:
1. Install Go https://go.dev/dl/.
2. CD into mur's path.
3. Run. `go run main.go structs.go <urls>`

**Comment by EmperorPenguin18** [comment]
Thank you!

**Comment by Sorrow446** [comment]
You're welcome. Let me know if there's any other problems.
